#!/bin/bash

[[ -z "$1" ]] && echo "Missing password name" && exit 1
[[ -z "$2" ]] && echo "Missing deletion time" && exit 1
sleep ${2} && gpaste-client delete-password "${1}" && notify-send -u low "Password ${1} deleted" >/dev/null
