#!/bin/bash
TIME=15


if [[ $(command -v gpaste-client) ]]; then
  clipboard="gpaste"
elif [[ $(command -v xclip) ]]; then
  clipboard="xclip"
elif [[ $(command -v xsel) ]]; then
  clipboard="xsel"
else
  notify-send -u critical "No clipboard tool found" "pass-tui supports gpaste, xclip, and xsel"
  exit 1
fi 


function notify() {
  notify-send -u low "$@"
}

function add_to_other_clipboard() {
  if [[ $clipboard == 'xclip' ]]; then
    echo "$3" | xclip -sel clip
  else
    echo "$3" | xsel -b
  fi
  notify "${2} $1 copied"
}

function copy_password() {
  echo -e "$3"
  # copy_password name label password
  if [[ $clipboard == 'gpaste' ]]; then
    gpaste-client add-password "$1" "$3"
    notify "${2} $1 copied" "Will be deleted in ${TIME} seconds"
    sleep $TIME && gpaste-client delete-password "$gpaste_id" && notify "${2} ${1} deleted" >/dev/null &
  else
    add_to_other_clipboard "$@"
  fi
}

function copy_field() {
  field=$(pass "$1" | grep -i "$3" | cut -d ' ' -f2-)
  if [[ -n $field ]]; then
    if [[ $clipboard == 'gpaste' ]]; then
      gpaste-client add "$field"
      notify "${2} ${1} copied"
    else
      add_to_other_clipboard "$1" "$2" "$field"
    fi
  else
    notify "${2} ${1} not found"
  fi
}

pass "$1" >/dev/null 2>&1 || exit 1
case $2 in
  'all')
    copy_password "$1" Entry "$(pass "$1")"
    ;;
  'password')
    copy_password "$1" Password "$(pass "$1" | head -1)"
    ;;
  'login')
    copy_field "$1" Login "login\|user"
    ;;
  'url')
    copy_field "$1" URL url
    ;;
  *)
    exit 1
    ;;
esac
